require "spectator"
require "../../../src/cassandra/dbapi"

alias TimeUuid = Cassandra::DBApi::TimeUuid

Spectator.describe TimeUuid do
  describe "#initialize" do
    it "can be autogenerated" do
      expect(TimeUuid.new.to_s.size).to eq(36)
    end
  end

  describe "#to_time" do
    it "returns a Time" do
      uuid = TimeUuid.new("00b69180-d0e1-11e2-8b8b-0800200c9a66")
      expect(uuid.to_time).to be > ::Time.utc(2013, 6, 9, 8, 45, 57)
      expect(uuid.to_time).to be < ::Time.utc(2013, 6, 9, 8, 45, 58)
    end
  end

  # TODO:
  # describe "#<=>" do
  #   it "sorts by the time component" do
  #
  #   end
  # end
end
