require "spec"
require "../../../src/cassandra/dbapi"

alias Uuid = Cassandra::DBApi::Uuid

describe Uuid do
  describe "#initialize" do
    it "can be autogenerated" do
      Uuid.new.to_s.size.should eq(36)
    end
  end

  # TODO:
  # describe "#<=>" do
  #   it "sorts by the time component" do
  #
  #   end
  # end
end
